spring:
  threads:
    virtual:
      enabled: true
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/ticketing?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&characterEncoding=UTF-8}
    username: ${SPRING_DATASOURCE_USERNAME:ticketing}
    password: ${SPRING_DATASOURCE_PASSWORD:ticketing}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: ${SPRING_JPA_DDL_AUTO:create-drop}
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.MySQL8Dialect
  data:
    redis:
      host: ${SPRING_DATA_REDIS_HOST:localhost}
      port: ${SPRING_DATA_REDIS_PORT:6379}
      ssl:
        enabled: ${SPRING_DATA_REDIS_SSL_ENABLED:false}
server:
  port: 8080
  tomcat:
    threads:
      max: 200

k6:
  base_url: ${K6_BASE_URL}
  cluster: ${K6_CLUSTER}
  subnet: ${K6_SUBNET}
  task-definition: ${K6_TASK_DEFINITION}

logging:
  level:
    com.ticketing: DEBUG
    org.hibernate.SQL: INFO
